"""Regenerate dependency diagrams from ROOTS, ROOT, and direct theory imports.

Run with Python 3.9+ from any directory. Standard Isabelle theory imports
are omitted from the foundation view; AFP imports are grouped by session.
"""
from pathlib import Path
from html import escape
import re

root = Path(__file__).resolve().parents[1]
assets = root / 'docs/assets'
sessions = (root / 'ROOTS').read_text(encoding='utf-8').split()
foundation = {}
for folder in ['Cross_Domain_State_Preservation', 'Regulatory_Action_Composition']:
    for path in sorted((root / folder).glob('*.thy')):
        match = re.search(r'(?m)^theory\s+(\w+)\s+imports\s+(.*?)\s+begin', path.read_text(encoding='utf-8'), re.S)
        assert match, path
        foundation[match[1]] = [word.strip('"').split('.')[-1] if not word.strip('"').startswith('ADS_Functor.')
                                  else 'ADS_Functor' for word in match[2].split()]
edges = sorted({(dep, name) for name, deps in foundation.items() for dep in deps
                if dep in foundation or dep == 'ADS_Functor'})
session_edges = set()
for name in sessions:
    text = (root / name / 'ROOT').read_text(encoding='utf-8')
    match = re.search(r'\bsession\s+' + re.escape(name) + r'\s*=\s*"?([\w-]+)"?\s*\+', text)
    assert match, name
    session_edges.add((match[1], name))
    extra = re.search(r'(?m)^\s+sessions\s+(.*?)^\s+theories\b', text, re.S)
    if extra:
        session_edges.update((dep.strip('"'), name) for dep in extra[1].split())
session_edges = sorted(session_edges)

def write(name, text):
    with (assets / name).open('w', encoding='utf-8', newline='\n') as handle:
        handle.write(text.rstrip() + '\n')

def mermaid(pairs, title):
    nodes = sorted({node for pair in pairs for node in pair})
    return '\n'.join(['%% ' + title, '%% Generated by scripts/render-architecture.py; arrows run from dependency to importer.',
                      'flowchart TB'] + [f'    {n.replace("-", "_")}["{n}"]' for n in nodes] +
                     [f'    {a.replace("-", "_")} --> {b.replace("-", "_")}' for a, b in pairs])

desc = 'Direct theory imports in the CDSP and RAC foundation. Arrows run from dependency to importing theory. Standard Isabelle library imports are omitted; ADS_Functor imports are grouped by AFP session. The separate session overview includes all seven registered artifacts.'
paths = {
    ('State_Preservation', 'Regulatory_Instance'): 'M350 173 V239',
    ('State_Preservation', 'Proof_Automation'): 'M310 173 V208 H145 V239',
    ('State_Preservation', 'Composition'): 'M410 173 V196 H862 V374 H844',
    ('Priority_Resolution', 'DQuencer_Instance'): 'M760 173 V239',
    ('Regulatory_Instance', 'DQuencer_Instance'): 'M434 270 H451 V325 H656 V262 H676',
    ('Proof_Automation', 'External_Instance'): 'M145 285 V307 H555 V285',
    ('Proof_Automation', 'Functor_Laws'): 'M125 285 V432 H300 V463',
    ('DQuencer_Instance', 'Functor_Laws'): 'M676 280 H661 V442 H450 V480 H434',
    ('Composition', 'Functor_Laws'): 'M740 397 V422 H374 V463',
    ('Regulatory_Instance', 'Functor_Laws'): 'M350 285 V463',
    ('Regulatory_Instance', 'Regulatory_Action_Composition'): 'M420 285 V410 H900 V614 H920',
    ('Functor_Laws', 'Hierarchy'): 'M310 509 V545 H145 V575',
    ('Functor_Laws', 'Canton_Bridge'): 'M390 509 V545 H555 V575',
    ('ADS_Functor', 'Functor_Laws'): 'M985 181 V451 H410 V463',
    ('ADS_Functor', 'Canton_Bridge'): 'M1035 181 V530 H600 V575',
}
assert set(paths) == set(edges), 'Direct imports changed: update the desktop routing before regenerating.'
svg = (assets / 'theory-architecture.svg').read_text(encoding='utf-8')
svg = re.sub(r'<title id="ta-title">.*?</title>', '<title id="ta-title">CDSP and RAC foundation: direct theory imports</title>', svg)
svg = re.sub(r'<desc id="ta-desc">.*?</desc>', '<desc id="ta-desc">' + desc + '</desc>', svg)
def arrows(external):
    color = '#8b76e8' if external else '#5f7aa8'
    marker = 'ta-arrow-ext' if external else 'ta-arrow'
    dash = ' stroke-dasharray="6 4"' if external else ''
    return '<g fill="none" stroke="' + color + '" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"' + dash + ' marker-end="url(#' + marker + ')">\n' + '\n'.join(
        f'    <path data-from="{a}" data-to="{b}" d="{paths[a,b]}"/>' for a,b in edges if (a == 'ADS_Functor') == external) + '\n  </g>\n\n  '
svg = re.sub(r'(?s)(<!-- edges: session-internal -->\s*).*?(<!-- edges: external AFP dependency -->)', lambda m: m[1] + arrows(False) + m[2], svg)
svg = re.sub(r'(?s)(<!-- edges: external AFP dependency -->\s*).*?(<!-- nodes -->)', lambda m: m[1] + arrows(True) + m[2], svg)
svg = svg.replace('imports within this repository', 'dependency → direct importer').replace('imports the external AFP session', 'external AFP dependency → importer')
write('theory-architecture.svg', svg)
write('theory-architecture.mmd', mermaid(edges, desc))

def start(width, height, title, detail):
    return [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">',
            f'<title id="title">{escape(title)}</title><desc id="desc">{escape(detail)}</desc>',
            '<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 1L9 5L0 9Z" fill="#91acd5"/></marker></defs>',
            f'<rect width="{width}" height="{height}" rx="20" fill="#0b142a"/>',
            '<g font-family="Arial,Segoe UI,sans-serif" fill="#e1eaf8">']
def text(x,y,value,size=20,color='#e1eaf8'):
    return f'<text x="{x}" y="{y}" font-size="{size}" fill="{color}">{escape(value)}</text>'

order = ['State_Preservation', 'Priority_Resolution', 'Proof_Automation', 'Regulatory_Instance',
         'Composition', 'DQuencer_Instance', 'External_Instance', 'Functor_Laws', 'Hierarchy',
         'Canton_Bridge', 'Regulatory_Action_Composition']
heights = {name: 68 + 29 * max(1, len([a for a,b in edges if b == name])) for name in order}
height = 154 + sum(heights.values()) + len(order)*15 + 72
mobile = start(600, height, 'CDSP and RAC foundation: direct imports', desc)
mobile += [text(28,46,'Foundation direct imports',27), text(28,80,'Each card names a theory and its direct dependencies.',18,'#a8bbd5'),
           text(28,108,'Standard Isabelle libraries omitted; AFP grouped.',18,'#a8bbd5')]
y = 136
for name in order:
    deps = [a for a,b in edges if b == name]
    mobile += [f'<g data-node="{name}"><rect x="24" y="{y}" width="552" height="{heights[name]}" rx="12" fill="#111f39" stroke="#49678e"/>',
               text(42,y+32,name,21), text(42,y+59,'Direct imports:',17,'#a8bbd5')]
    if deps:
        for i,dep in enumerate(deps):
            mobile += [f'<g data-from="{dep}" data-to="{name}">' + text(58,y+85+i*29,dep,20) + '</g>']
    else:
        mobile += [text(58,y+85,'Standard Isabelle library only',19,'#a8bbd5')]
    mobile += ['</g>']; y += heights[name] + 15
mobile += [text(28,y+27,'The full session chain is shown in the overview.',18,'#a8bbd5'),'</g></svg>']
write('theory-architecture-mobile.svg','\n'.join(mobile))

chain = ['Cross_Domain_State_Preservation','Regulatory_Action_Composition','Cross_Chain_Message_Integrity',
         'Preemptive_Lock_Correctness','Evidence_Atomic_Binding','Evidence_Binding_Composition']
assert set(sessions) == set(chain + ['Protected_Behavior_Obstructions'])
assert set(session_edges) == set(zip(chain,chain[1:])) | {('HOL-Library',chain[0]),('HOL-Eisbach',chain[0]),('ADS_Functor',chain[0]),('HOL','Protected_Behavior_Obstructions')}
labels = {
    chain[0]: ['Cross-Domain State','Preservation'], chain[1]: ['Regulatory Action','Composition'],
    chain[2]: ['Cross-Chain Message','Integrity'], chain[3]: ['Preemptive Lock','Correctness'],
    chain[4]: ['Evidence Atomic','Binding'], chain[5]: ['Evidence Binding','Composition'],
    'Protected_Behavior_Obstructions':['Protected Behavior','Obstructions'],
    'HOL-Library':['HOL-Library'], 'HOL-Eisbach':['HOL-Eisbach'], 'ADS_Functor':['AFP ADS_Functor'], 'HOL':['HOL']}
detail = 'All seven ROOTS-registered artifact sessions. Six form the CDSP to Evidence Binding Composition parent chain. Protected Behavior Obstructions independently extends HOL. Additional direct CDSP session dependencies are HOL-Library, HOL-Eisbach, and AFP ADS_Functor. Auxiliary audit sessions are not separate artifact entries.'
for narrow in [False, True]:
    width,height = (600,1450) if narrow else (1120,830)
    boxes = {}
    if narrow:
        for i,name in enumerate(chain): boxes[name]=(32,250+i*125,536,80)
        boxes.update({'HOL-Library':(24,126,174,58),'HOL-Eisbach':(214,126,174,58),'ADS_Functor':(404,126,172,58),
                      'HOL':(180,1090,240,58),'Protected_Behavior_Obstructions':(32,1190,536,88)})
    else:
        for i,name in enumerate(chain): boxes[name]=(40+(i%3)*355,260+(i//3)*188,300,90)
        boxes.update({'HOL-Library':(40,124,200,58),'HOL-Eisbach':(280,124,200,58),'ADS_Functor':(520,124,200,58),
                      'HOL':(40,649,190,64),'Protected_Behavior_Obstructions':(320,635,410,88)})
    drawing = start(width,height,'Repository session dependencies',detail)
    drawing += [text(28,48,'Repository session dependencies',27),text(28,83,'Seven registered artifacts · dependency → child',19,'#a8bbd5')]
    for a,b in session_edges:
        x,y,w,h=boxes[a];xx,yy,ww,hh=boxes[b]
        if not narrow and a in chain and b in chain and chain.index(a)==2:
            path=f'M{x+w/2} {y+h} V399 H{xx+ww/2} V{yy}'
        elif not narrow and y==yy or (not narrow and a=='HOL'):
            path=f'M{x+w} {y+h/2} H{xx}'
        else:
            middle=(y+h+yy)/2
            path=f'M{x+w/2} {y+h} V{middle} H{xx+ww/2} V{yy}'
        drawing += [f'<path data-from="{a}" data-to="{b}" d="{path}" fill="none" stroke="#91acd5" stroke-width="2" marker-end="url(#arrow)"/>']
    for name,(x,y,w,h) in boxes.items():
        external=name not in sessions
        drawing += [f'<g data-node="{name}"><rect x="{x}" y="{y}" width="{w}" height="{h}" rx="12" fill="{("#201b3e" if external else "#11233c")}" stroke="{("#9583db" if external else "#527aa1")}"/>']
        for j,label in enumerate(labels[name]):
            size=18 if external else (24 if narrow else 22)
            drawing += [f'<text x="{x+w/2}" y="{y+h/2+(j-(len(labels[name])-1)/2)*27+7}" text-anchor="middle" font-size="{size}">{escape(label)}</text>']
        drawing += ['</g>']
    footer = 1330 if narrow else 770
    drawing += [text(28,footer,'Protected Behavior Obstructions is independent.',18,'#a8bbd5'),
                text(28,footer+30,'Auxiliary audit sessions are separate from this catalog.',18,'#a8bbd5'),'</g></svg>']
    write('session-architecture'+('-mobile' if narrow else '')+'.svg','\n'.join(drawing))
write('session-architecture.mmd',mermaid(session_edges,detail))
print(f'Architecture generated: {len(sessions)} registered sessions, {len(session_edges)} session edges, {len(edges)} foundation edges.')
